name: Deploy to AWS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 034362052544.dkr.ecr.us-east-1.amazonaws.com

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      - name: Tag Docker image
        run: docker tag auth-lambda:latest 034362052544.dkr.ecr.us-east-1.amazonaws.com/auth-lambda:latest

      - name: Push Docker image to Amazon ECR
        run: docker push 034362052544.dkr.ecr.us-east-1.amazonaws.com/auth-lambda:latest

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Deploy CDK stack
        run: cdk deploy --require-approval never