name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      # Set up AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 034362052544.dkr.ecr.us-east-1.amazonaws.com

      # Build the Docker image
      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      # Tag the image
      - name: Tag Docker image
        run: docker tag auth-lambda:latest 034362052544.dkr.ecr.us-east-1.amazonaws.com/auth-lambda:latest

      # Push the Docker image to ECR
      - name: Push Docker image to Amazon ECR
        run: docker push 034362052544.dkr.ecr.us-east-1.amazonaws.com/auth-lambda:latest

      # Install Node.js (for AWS CDK)
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Install AWS CDK
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # Deploy the CDK stack
      - name: Deploy CDK stack
        run: cdk deploy --require-approval never
